#!/usr/bin/env bash
# File script that transfers file from client to server over SCP
# That is one way of publishing your website pages to your server.

# Handle requirement error
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  f_path="$1"
  server_ip="$2"
  user="$3"
  key_path="$4"
scp -o StrictHostKeyChecking=no -i "$key_path" "$f_path" "$user"@"$server_ip":~/
# Disable strict host checking
fi
