#!/usr/bin/env bash
# This file script set an nginix configuaration and includes
# a string text to display, when a GET method request is made

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Re-configur the default file to read from index.html
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
# Write to defined file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Lets restart nginx serice
sudo service nginx restart
