#!/usr/bin/env bash
# This is a redirection configuration on nginx

apt-get update
apt-get install -y nginx

sed -i '/location \/ {/a \'
'    location /redirect_me { \
        return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

service nginx reload
