#!/usr/bin/env bash
# This is a 404 directie and redirection of nginx

apt-get update
apt-get install -y nginx

# Configure Nginx for 301 redirection
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name web-01;

    # Custom 404 page
    error_page 404 /custom_404;

    location = /custom_404 {
        internal;
        return 404 "Ceci n'est pas une page";
    }

    location /redirect_me {
        return 301 http://example.com/destination;
    }

    # 404 not found
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Reload Nginx to apply changes
systemctl reload nginx
