#!/usr/bin/env bash
# This script sets up an Nginx configuration with a custom 404 page.

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow HTTP traffic through UFW for Nginx
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file with "Hello World!" for the default page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Create a custom 404 error page with the required content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx for redirection and custom 404 page
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80 default_server;
    server_name _;

    location /redirect_me/ {
        # Get the used URL
        set \$redirect_url \$request_uri;
        return 301 \$redirect_url;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Create a symbolic link to enable the redirection site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart

exit 0

