#!/usr/bin/env bash
# This script configures nginx to set up a 404 not found

apt-get update
apt-get install -y nginx

sed -i '/server {/a \
    error_page 404 /404.html; \
    location = /404.html { \
        root /usr/share/nginx/html; \
        internal; \
        return 404 "<html><head><title>404 Not Found</title></head><body>Ceci n'\''est pas une page</body></html>"; \
    }' /etc/nginx/sites-available/default

service nginx reload
