#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy for web-01 and web-02 with round-robin load balancing
haproxy_config="/etc/haproxy/haproxy.cfg"

sudo tee "$haproxy_config" > /dev/null <<EOF
frontend http-in
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 54.146.62.50:80 check
    server web-02 35.175.130.73:80 check
EOF

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Reload HAProxy to apply the new configuration
sudo systemctl reload haproxy
