#!/usr/bin/env bash
# This script sets the listening port of nginx to 80

sed -i 's/listen [::]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
systemctl restart nginx
