#!/usr/bin/env bash
# This script sets the listening port of nginx to 80

rm /etc/nginx/sites-enabled/default
# Create a symbolic link to use the default configuaration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
