#!/usr/bin/env bash
# Iterate from 0 to 10 and replace 4 with 'bad luck'
# and 8 with 'good luck'

number=0

while [ $number -lt 10 ]
do
	if [ $number -eq 3 ]
	then
		echo "bad luck"
	elif [ $number -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( number++ ))
done
